apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azure-postgresql-db
spec:
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: postgresql
    repoURL: https://github.com/wael2000/azure-service-operator
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true